### ISSUE TITLE
video id and the corresponding captions

### ISSUE THREAD

**Issue by tjumc** [MarcusNerva/HMN#12]
Thank you for your contribution, I benefited a lot. 
For further study,I wonder how to get the original video id and the corresponding captions？I want to check the difference between my output of predict captions and the original video.

**Comment by syl0107** [comment]
Hello, I downloaded the original video of the dataset on the Internet, I want to see the video content corresponding to the output description of a certain ID, but the description of the model output does not correspond to the video content with the same ID name, I saw your question, so I want to ask if your problem is solved? How do you view the original video corresponding to the caption?
